#!/bin/sh
#
# Usage: gputest.sh
# Change job name and email address as needed 
#        
 
# ------Sirisha Bojjireddy---- ---
#$ -N a10_output
#$ -S /bin/sh
# Make sure that the .e and .o file arrive in the
#working directory
#$ -cwd
#Merge the standard out and standard error to one file
#$ -j y
# Send mail at submission and completion of script
#$ -m be

# Request a GPU
#$ -q datasci -l hostname=node412
# Request one gpu (max two)
#$ -l gpu=1
/bin/echo Running on host: `hostname`.
/bin/echo In directory: `pwd`
/bin/echo Starting on: `date`



#load the singularity module
module load singularity

#run the singularity command
#singularity exec --nv /opt/singularity_images/deeplearning_cuda_10.1_ubuntu-16.04_python-3.6_v1.2.sif python train.py ./data/test_image.npy ./models/mlp20node_model ./models/bb_model.h5 > out_train
singularity exec --nv /opt/singularity_images/deeplearning_cuda_10.1_ubuntu-16.04_python-3.6_v1.2.sif python test.py ./data/processed_test_data.npy ./models/mlp20node_model ./models/bb_model.h5 > out_test
